### ISSUE TITLE
Sonarqube coverage is 0%

### ISSUE THREAD

**Issue by eloo** [kordamp/kordamp-gradle-plugins#357]
Hi,

sadly i'm unable to get the coverage working with sonar and jacoco.
My problem really sounds like the issue from #335 but i'm not using a multi-module.. so there is just one module with multiple source sets (different tests)

The jacoco report is working as expected and shows the coverage like i'm expecting but in sonar there is something not working :( 

What i see in sonar:
- Unit tests has a proper value
- Lines of code to cover looks also good
- Coverage is not okay and show everytime 0%

Project setup looks like this:
```
.
├── build
│   ├── classes
│   │   └── java
│   │       ├── archUnitTest
│   │       ├── integrationTest
│   │       ├── main
│   │       └── test
│   ├── jacoco
│   │   ├── aggregate.exec
│   │   ├── archUnitTest.exec
│   │   ├── integrationTest.exec
│   │   └── test.exec
│   ├── reports
│   │   ├── jacoco
│   │   │   ├── aggregate
│   │   │   │   ├── html
│   │   │   │   └── jacocoTestReport.xml
│   │   │   ├── archUnitTest
│   │   │   │   ├── html
│   │   │   │   └── jacocoTestReport.xml
│   │   │   ├── integrationTest
│   │   │   │   ├── html
│   │   │   │   └── jacocoTestReport.xml
│   │   │   └── test
│   │   │       ├── html
│   │   │       └── jacocoTestReport.xml
│   ├── sonar
│   │   ├── class-mapping.csv
│   │   └── report-task.txt
├── build.gradle
├── gradle.properties
├── settings.gradle
├── src
│   ├── archUnitTest
│   │   └── java
│   ├── integrationTest
│   │   ├── java
│   ├── main
│   │   ├── java
│   └── test
│       ├── java
```

The effective config looks like this
```
coverage:
    jacoco:
        enabled: true
        aggregateExecFile: /Users/xxx/git/xxx/xxx-service/build/jacoco/aggregate.exec
        aggregateReportHtmlFile: /Users/xxx/git/xxx/xxx-service/build/reports/jacoco/aggregate/html
        aggregateReportXmlFile: /Users/xxx/git/xxx/xxx-service/build/reports/jacoco/aggregate/jacocoTestReport.xml
        toolVersion: 0.8.5
        includeProjectDependencies: false
 
quality:
    sonar:
        enabled: true
        hostUrl: https://sonarcloud.io
        username: dummy-value
        projectKey: XXX:xxx-service
        ignoreFailures: true
        configProperties:
            sonar.projectName: XXXX
            sonar.branch.name: local
```

I really don't know whats wrong..
I've tested already at least the following things:
- Older version (0.34.0)
- Set the jacoco xml path manually

My best guess is that something is wrong in the sonarqube properties. But i'm also not sure how i can print them to the console.

Thanks
